# Generated by Django 2.2.4 on 2020-08-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen_referencial',
            field=models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Imágen Referencial'),
        ),
    ]
